[project]
name = "comfydock_pinokio"
version = "2.0.0"
description = "A manager for ComfyUI environments using Docker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "comfydock-server>=0.3.0",
]
